run_name : "test_2"
models : "gan"
dataset : "datasets/afhq/latents"

training:
  optimizer: "nadam"
  batch_size: 64
  scaling_factor : 256
  generator_lr: 0.00005
  discriminator_lr: 0.00001
  epochs : 1000
  plot_gen_images_freq: 100
  accumulated_steps: 1

use_wandb: true